- hosts: all
  become: true
  vars:
    severity_colors:
      normal: 3066993    # Green
      warning: 16776960  # Yellow
      critical: 15158332 # Red
  tasks:
    - name: Get hostname
      command: hostname -f
      register: hostname
      changed_when: false

    - name: Get OS info
      shell: grep PRETTY_NAME /etc/os-release | cut -d'"' -f2
      register: os_info
      changed_when: false

    - name: Get system uptime
      shell: uptime -p | sed 's/up //'
      register: uptime
      changed_when: false

    # Get root partition usage only
    - name: Get root partition usage
      shell: df -h / | awk 'NR==2 {print $2","$3","$4","$5}'
      register: root_usage
      changed_when: false

    # Get simple memory stats and calculate percentage
    - name: Get memory usage
      shell: free | awk 'NR==2 {printf "%.0f,%.1fG,%.1fG,%.1f", ($2-$7)/$2*100, $2/1024/1024, ($2-$7)/1024/1024, $7/1024/1024}'
      register: memory_usage
      changed_when: false

    - name: Get highest disk usage percentage
      shell: df --output=pcent / | tail -n 1 | tr -d '% '
      register: highest_disk_percent
      changed_when: false

    - name: Set parsed values
      set_fact:
        root_stats: "{{ root_usage.stdout.split(',') }}"
        mem_stats: "{{ memory_usage.stdout.split(',') }}"
        disk_warning: "{{ '⚠️ ' if highest_disk_percent.stdout|int >= 80 else '' }}"
        ram_warning: "{{ '⚠️ ' if mem_stats[0]|int >= 80 else '' }}"
        message_color: "{{ severity_colors.warning if highest_disk_percent.stdout|int >= 80 or mem_stats[0]|int >= 80 else severity_colors.normal }}"

    - name: Send Discord notification
      uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        body_format: json
        body: |
          {
            "username": "System Monitor",
            "embeds": [
              {
                "author": {
                  "name": "{{ hostname.stdout }}"
                },
                "title": "System Status Report",
                "description": "**OS**: {{ os_info.stdout }}\n**Uptime**: {{ uptime.stdout }}",
                "color": {{ message_color }},
                "fields": [
                  {
                    "name": "{{ disk_warning }}Root Partition",
                    "value": "Total: {{ root_stats[0] }} | Used: {{ root_stats[1] }} | Free: {{ root_stats[2] }} ({{ root_stats[3] }})",
                    "inline": true
                  },
                  {
                    "name": "{{ ram_warning }}Memory",
                    "value": "Total: {{ mem_stats[1] }}G | Used: {{ mem_stats[2] }}G | Available: {{ mem_stats[3] }}G ({{ mem_stats[0] }}%)",
                    "inline": true
                  }
                ],
                "footer": {
                  "text": "Last updated: {{ ansible_date_time.iso8601 }}"
                }
              }
            ]
          }
        headers:
          Content-Type: application/json
        status_code: [204, 200]
      when: highest_disk_percent.stdout|int >= 80 or mem_stats[0]|int >= 80
