- hosts: all
  become: true
  vars:
    severity_colors:
      normal: 3066993    # Green
      warning: 16776960  # Yellow
      critical: 15158332 # Red
  tasks:
    - name: Get hostname
      command: hostname -f
      register: hostname
      changed_when: false

    - name: Get OS info
      command: cat /etc/os-release
      register: os_info
      changed_when: false

    - name: Get system uptime
      command: uptime -p
      register: uptime
      changed_when: false

    - name: Get disk usage for all partitions
      command: df -h --output=source,target,size,used,avail,pcent
      register: disk_info
      changed_when: false

    - name: Get memory info
      command: free -h
      register: memory_info
      changed_when: false

    - name: Get highest disk usage percentage
      shell: df --output=pcent / | tail -n 1 | tr -d '% '
      register: highest_disk_percent
      changed_when: false

    - name: Set message color based on severity
      set_fact:
        message_color: >-
          {{
            severity_colors.critical if highest_disk_percent.stdout|int > 90
            else severity_colors.warning if highest_disk_percent.stdout|int > 80
            else severity_colors.normal
          }}

    # Debug the body before sending
    - name: Print Discord message body
      debug:
        msg: |
          {
            "username": "System Monitor",
            "embeds": [
              {
                "author": {
                  "name": "{{ hostname.stdout }}"
                },
                "title": "System Status Report",
                "description": "Status report for system monitoring",
                "color": {{ message_color }},
                "fields": [
                  {
                    "name": "System Information",
                    "value": "**OS**: {{ os_info.stdout_lines[1] | regex_replace('^NAME=|\"', '') }}\n**Uptime**: {{ uptime.stdout }}",
                    "inline": false
                  },
                  {
                    "name": "Memory Usage",
                    "value": "```{{ memory_info.stdout }}```",
                    "inline": false
                  },
                  {
                    "name": "Disk Usage",
                    "value": "```{{ disk_info.stdout }}```",
                    "inline": false
                  }
                ],
                "footer": {
                  "text": "Last updated: {{ ansible_date_time.iso8601 }}"
                }
              }
            ]
          }
          
    - name: Send Discord notification
      uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        body_format: json
        body: |
          {
            "username": "System Monitor",
            "embeds": [
              {
                "author": {
                  "name": "{{ hostname.stdout }}"
                },
                "title": "System Status Report",
                "description": "Status report for system monitoring",
                "color": {{ message_color }},
                "fields": [
                  {
                    "name": "System Information",
                    "value": "**OS**: {{ os_info.stdout_lines[1] | regex_replace('^NAME=|\"', '') }}\n**Uptime**: {{ uptime.stdout }}",
                    "inline": false
                  },
                  {
                    "name": "Memory Usage",
                    "value": "```{{ memory_info.stdout }}```",
                    "inline": false
                  },
                  {
                    "name": "Disk Usage",
                    "value": "```{{ disk_info.stdout }}```",
                    "inline": false
                  }
                ],
                "footer": {
                  "text": "Last updated: {{ ansible_date_time.iso8601 }}"
                }
              }
            ]
          }
        headers:
          Content-Type: application/json
        status_code: [204, 200]
      when: highest_disk_percent.stdout|int > 80
