- hosts: all

  become: true
  tasks:
    - name: Get disk usage of root partition
      shell: df -h / | awk 'NR==2 {print $5" used ("$3" of "$2")"}'
      register: disk_usage

    - name: Get root partition percentage only
      shell: df -h / | awk 'NR==2 {print $5}' | sed 's/%//'
      register: disk_percent

    # Send Discord message with disk usage info
    - name: Send Discord message
      uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        body_format: json
        body: '{ "content": "Disk Usage Report for {{ inventory_hostname }}:\nRoot partition: {{ disk_usage.stdout }}\n{% if disk_percent.stdout|int > 80 %}⚠️ WARNING: High disk usage detected!{% endif %}"}'
        headers:
          Content-Type: application/json
        status_code: 204
      when: disk_percent.stdout|int > 80